import { chromium, dir, amostras, ENDERECO } from '../comum.mjs';
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport:{width:390,height:844}, deviceScaleFactor:2 })).newPage();
page.on('pageerror', e => console.log('PAGEERROR:', e.message));
// nenhuma chamada de rede pode sair por causa do PDF
const fora = [];
page.on('request', r => { const u=r.url(); if (!/127\.0\.0\.1|localhost|^data:|^blob:/.test(u)) fora.push(u); });
const folha = () => page.locator('#folha');
await page.goto(ENDERECO, { waitUntil:'networkidle' });
await page.waitForTimeout(400);
await page.evaluate(() => { localStorage.clear(); sessionStorage.clear(); });
await page.reload({ waitUntil:'networkidle' }); await page.waitForTimeout(1400);
await page.evaluate(() => { document.getElementById('entrada').scrollTop = 99999; });
await page.click('.btn-dourado:has-text("Criar minha conta")'); await page.waitForTimeout(500);
const c = page.locator('.ent-campo input');
await c.nth(0).fill('Vitor'); await c.nth(1).fill('w'+Date.now() + '-' + process.pid + '@exemplo.com'); await c.nth(3).fill('senha123');
await page.click('.btn-dourado:has-text("Continuar")'); await page.waitForTimeout(400);
await page.click('.btn-dourado:has-text("Continuar")'); await page.waitForTimeout(400);
await page.click('.btn-dourado:has-text("Criar minha conta")'); await page.waitForTimeout(3000);
await page.click('#telaInicio .cartao-acao:has-text("+ Nova")'); await page.waitForTimeout(500);
await folha().locator('input.entrada[type=text]').first().fill('C6 Bank');
await page.click('#folha .btn-ouro'); await page.waitForTimeout(900);
await page.click('#navegacao button:has-text("Mais")'); await page.waitForTimeout(800);
await page.screenshot({ path: dir+'/d00-mais.png' });
const antes = fora.length;
let arquivo = amostras + '/c6-senha-aes256.pdf';
page.on('filechooser', async fc => { await fc.setFiles(arquivo); });
await page.click('#telaMais .linha:has-text("Importar extrato")'); await page.waitForTimeout(2500);
await page.screenshot({ path: dir+'/d01-senha.png' });
await folha().locator('input[type=password]').fill('12345678');
await page.click('#folha .btn-ouro:has-text("Abrir")'); await page.waitForTimeout(3000);
await page.screenshot({ path: dir+'/d02-conferir.png' });
await page.evaluate(() => { document.getElementById('folha').scrollTop = 99999; });
await page.waitForTimeout(400);
await page.screenshot({ path: dir+'/d03-fim.png' });
console.log('pedidos para fora durante a leitura do PDF:', fora.length - antes, fora.slice(antes));
await page.click('#folha .btn-ouro'); await page.waitForTimeout(900);
console.log('confirmação:', await page.textContent('#dialogoTitulo'));
await page.click('#dialogoAcoes button:has-text("Sim")'); await page.waitForTimeout(2500);
await page.screenshot({ path: dir+'/d04-transacoes.png' });
console.log('importado:', (await page.textContent('#telaTransacoes')).replace(/\s+/g,' ').slice(0,110));
await browser.close();
