import { chromium, dir, amostras, ENDERECO } from '../comum.mjs';
const browser = await chromium.launch();
const page = await (await browser.newContext({ viewport:{width:390,height:844} })).newPage();
page.on('pageerror', e => console.log('PAGEERROR:', e.message));
const folha = () => page.locator('#folha');
let arquivo = amostras + '/c6-grande.pdf';
page.on('filechooser', async fc => { await fc.setFiles(arquivo); });
await page.goto(ENDERECO, { waitUntil:'networkidle' });
await page.waitForTimeout(400);
await page.evaluate(() => { localStorage.clear(); sessionStorage.clear(); });
await page.reload({ waitUntil:'networkidle' }); await page.waitForTimeout(1800);
await page.evaluate(() => { document.getElementById('entrada').scrollTop = 99999; });
await page.click('.btn-dourado:has-text("Criar minha conta")'); await page.waitForTimeout(500);
const c = page.locator('.ent-campo input');
await c.nth(0).fill('Vitor'); await c.nth(1).fill('d68'+Date.now() + '-' + process.pid + '@exemplo.com'); await c.nth(3).fill('senha123');
await page.click('.btn-dourado:has-text("Continuar")'); await page.waitForTimeout(400);
await page.click('.btn-dourado:has-text("Continuar")'); await page.waitForTimeout(400);
await page.click('.btn-dourado:has-text("Criar minha conta")'); await page.waitForTimeout(3000);
await page.click('#navegacao button:has-text("Mais")'); await page.waitForTimeout(800);
await page.click('#telaMais label.linha:has-text("Importar extrato")');
await page.waitForSelector('#folha input[type=password]', { timeout: 40000 });
await folha().locator('input[type=password]').fill('12345678');
await page.click('#folha .btn-ouro:has-text("Abrir")');
await page.waitForSelector('#folha .paginas', { timeout: 60000 }); await page.waitForTimeout(1000);

const r = await page.evaluate(async () => {
  const f = document.getElementById('folha');
  f.scrollTop = 1400;
  const marcas = ['inicial: ' + f.scrollTop + ' (altura ' + f.scrollHeight + ')'];
  const b = [...f.querySelectorAll('.paginas .btn-mini')].find(x=>/Próximos/.test(x.textContent));
  b.click();
  marcas.push('logo apos click: ' + f.scrollTop);
  await new Promise(r => requestAnimationFrame(r));
  marcas.push('1 frame: ' + document.getElementById('folha').scrollTop);
  await new Promise(r => setTimeout(r, 100));
  marcas.push('100ms: ' + document.getElementById('folha').scrollTop);
  await new Promise(r => setTimeout(r, 800));
  marcas.push('900ms: ' + document.getElementById('folha').scrollTop +
    ' (altura ' + document.getElementById('folha').scrollHeight + ')');
  return marcas;
});
r.forEach(m => console.log('  ', m));
await browser.close();
